#####################################
# 具体配置 可以参考
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
#####################################
# banner
banner:
  charset: UTF-8
  location: classpath:banner.txt

# 应用属性配置
application:
  name: schedule-job
  version: v1.0.0

# 服务端配置
server:
  port: ${port:54321}
  contextPath: /
  compression:
    enabled: true

# spring配置
spring:
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  mvc:
    favicon:
      enabled: false
  profiles:
    include: db_common

# multipart 配置
multipart:
  enabled: true
  file-size-threshold: 0
  location: /
  max-file-size: 1Mb
  max-request-size: 10Mb

# MyBatis
mybatis:
  mapperLocations: classpath:/mapper/**/*Mapper.xml
  configLocation: classpath:mybatis-config.xml

# logback config
# You cannot use extensions in the standard logback.xml configuration file since it’s loaded too early.
# You need to either use logback-spring.xml or define a logging.config property.
# path不以'/'开头时，默认是从此类所在的包下取资源；
# path以'/'开头时，则是从项目的ClassPath根下获取资源。在这里'/'表示ClassPath
# Class.getResource和ClassLoader.getResource的区别
logging:
  config: classpath:config/logback.xml

  # Used in default log configuration if defined.
#  file: schelude.log
#  path: /

