# 应用属性配置
application:
  name: schedule-job
  version: v1.0.0

# 服务端配置
server:
  port: ${port:54321}
  contextPath: /
  compression:
    enabled: true

# spring配置
spring:
  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true

# MyBatis
mybatis:
  mapperLocations: classpath:/mapper/**/*Mapper.xml
  configLocation: classpath:mybatis-config.xml

# logback config
# You cannot use extensions in the standard logback.xml configuration file since it’s loaded too early.
# You need to either use logback-spring.xml or define a logging.config property.