###################################
# 缺省redis地址 dev
###################################
cache:
  redis:
    host: redis.addr.dev
    port: 6378
    password:
    pool:
      min-idle: 2
      max-idle: 5
      max-total: 10
      max-wait: 1000
      minEvictableIdleTimeMillis: 60 * 1000
      numTestsPerEvictionRun: 5
      blockWhenExhausted: true
      fairness: true
      testWhileIdle: true
      testOnBorrow: true